name: Build and Release Binaries

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            separator: ":"
            ext: ""
          - os: windows-latest
            separator: ";"
            ext: ".exe"
          - os: macos-latest
            separator: ":"
            ext: ""

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install .
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --add-data "src/askgem/locales/*${{ matrix.separator }}askgem/locales" --name askgem run.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: askgem-${{ matrix.os }}
          path: dist/askgem${{ matrix.ext }}

      - name: Attach to Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: dist/askgem${{ matrix.ext }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
